people:
- name: Nyashinski
  aliases:
  - Nyashinski
  - '#Nyashinski'
  facebook_pages:
  - OfficialNyashinski
  hashtags:
  - '#Nyashinski'
  instagram_users: []
  instagram_hashtags:
  - Nyashinski
- name: Sauti Sol
  aliases:
  - Sauti Sol
  - Bien
  - Savara
  - '#SautiSol'
  facebook_pages:
  - sautisol
  hashtags:
  - '#SautiSol'
  instagram_users: []
  instagram_hashtags:
  - SautiSol
- name: Otile Brown
  aliases:
  - Otile Brown
  - '#OtileBrown'
  - OB
  facebook_pages:
  - otilebrownmusic
  hashtags:
  - '#OtileBrown'
  instagram_users: []
  instagram_hashtags:
  - OtileBrown
- name: burna boy
  aliases:
  - burna boy
  - '#burna boy'
  facebook_pages: []
  hashtags: []
  instagram_users: []
  instagram_hashtags: []
- name: elon musk
  aliases:
  - elon musk
  - '#elon musk'
  facebook_pages: []
  hashtags: []
  instagram_users: []
  instagram_hashtags: []
- name: Arsenal
  aliases:
  - Arsenal
  - '#Arsenal'
  facebook_pages: []
  hashtags: []
  instagram_users: []
  instagram_hashtags: []
- name: william ruto
  aliases:
  - william ruto
  - '#william ruto'
  facebook_pages: []
  hashtags: []
  instagram_users: []
  instagram_hashtags: []
- name: wantam
  aliases:
  - wantam
  - '#wantam'
  facebook_pages: []
  hashtags: []
  instagram_users: []
  instagram_hashtags: []
- name: manchester united
  aliases:
  - manchester united
  - '#manchester united'
  facebook_pages: []
  hashtags: []
  instagram_users: []
  instagram_hashtags: []
